name: django
channels:
  - defaults
dependencies:
  - asgiref=3.4.1
  - backcall=0.2.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - colorama=0.4.4
  - decorator=5.0.9
  - django=3.2.5
  - freetype=2.10.4
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jpeg=9b
  - libpng=1.6.37
  - libpq=12.2
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - olefile=0.46
  - openssl=1.1.1l
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.2
  - prompt-toolkit=3.0.17
  - psycopg2=2.8.6
  - pygments=2.10.0
  - python=3.9.5
  - pytz=2021.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - sqlparse=0.4.1
  - tk=8.6.10
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - mysqlclient==2.0.3
  - lxml==4.6.3
  - pip:
      - docxcompose==1.3.3
      - docxtpl==0.12.0
      - gunicorn==20.1.0
      - jinja2==3.0.1
      - markupsafe==2.0.1
      - python-docx==0.8.11
      - six==1.16.0
